[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "python313Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && python -m pip install --upgrade pip",
  ". /opt/venv/bin/activate && python -m pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"